### ISSUE TITLE
Duplicate Filter registration for 'springSecurityFilterChain'

### ISSUE THREAD

**Issue by tulipneo** [Fruzenshtein/security-spr#5]
Hi
Alex or any one who are listening!
After fixing common-logger problem i m stuck up with 
Duplicate Filter registration for 'springSecurityFilterChain' appears.
Now i removed the repo as u adviced.the Duplicate error gone but i get bellow exception.
"No WebApplicationContext found: no ContextLoaderListener registered?"
Any pointers or help?

Br
Neo

**Comment by Fruzenshtein** [comment]
Check the Initializer class. It extends AbstractAnnotationConfigDispatcherServletInitializer class. The class in its turn provide ContextLoaderListener. Try to dig in this direction

**Comment by tulipneo** [comment]
Hi Alex,
I am a totally Newbie in this area.
I tried all yours other example Normal MVC,Rest MVC and was trying to explore The security Feature.I thought it would be  a good starting point but am stuck here.My Initializer Class looks like bellow:

Any help with this.

Br
Neo

package com.sprsec.init;

import org.springframework.core.annotation.Order;
import org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer;

@Order(1)
public class Initializer extends
        AbstractAnnotationConfigDispatcherServletInitializer {

    @Override
    protected Class<?>[] getRootConfigClasses() {
        return new Class[] { RootConfig.class, SecurityConfig.class };
    }

    @Override
    protected Class<?>[] getServletConfigClasses() {
        return new Class[] { WebAppConfig.class };
    }

    @Override
    protected String[] getServletMappings() {
        return new String[] { "/" };
    }

}

On Tuesday, 25 March 2014 6:16 PM, Alex notifications@github.com wrote:

Check the Initializer class. It extends AbstractAnnotationConfigDispatcherServletInitializer class. The class in its turn provide ContextLoaderListener. Try to dig in this direction

**Comment by tulipneo** [comment]
Sorry I attached wrong sources:

package com.sprhib.init;

import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.ServletRegistration.Dynamic;

import org.springframework.web.WebApplicationInitializer;
import org.springframework.web.context.ContextLoaderListener;
import org.springframework.web.context.support.AnnotationConfigWebApplicationContext;
import org.springframework.web.servlet.DispatcherServlet;

public class Initializer implements WebApplicationInitializer {

    public void onStartup(ServletContext servletContext)
            throws ServletException {
        AnnotationConfigWebApplicationContext ctx = new AnnotationConfigWebApplicationContext();
        ctx.register(WebAppConfig.class);
        servletContext.addListener(new ContextLoaderListener(ctx));

        ctx.setServletContext(servletContext);

        Dynamic servlet = servletContext.addServlet("dispatcher", new DispatcherServlet(ctx));
        servlet.addMapping("/");
        servlet.setLoadOnStartup(1);
    }

}

Br
Neo

On , tulip neo neo.tulip@yahoo.com wrote:

Hi Alex,
I am a totally Newbie in this area.
I tried all yours other example Normal MVC,Rest MVC and was trying to explore The security Feature.I thought it would be  a good starting point but am stuck here.My Initializer Class looks like bellow:

Any help with this.

Br
Neo

package com.sprsec.init;

import org.springframework.core.annotation.Order;
import org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer;

@Order(1)
public class Initializer extends
        AbstractAnnotationConfigDispatcherServletInitializer {

    @Override
    protected Class<?>[]
 getRootConfigClasses() {
        return new Class[] { RootConfig.class, SecurityConfig.class };
    }

    @Override
    protected Class<?>[] getServletConfigClasses() {
        return new Class[] { WebAppConfig.class };
    }

    @Override
    protected String[] getServletMappings() {
        return new String[] { "/" };
    }

}

On Tuesday, 25 March 2014 6:16 PM, Alex notifications@github.com wrote:

Check the Initializer class. It extends AbstractAnnotationConfigDispatcherServletInitializer class. The class in its turn provide ContextLoaderListener. Try to dig in this direction

**Comment by qiuzuhui** [comment]
comment the filter in web.xml , will fix this problem
